### PR TITLE
Enhance TIFF format detection

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Enhance `tiff` image format detection approach.

The enhanced approach is as follows:
- Firstly, reading the two bytes to check it's `II` or `MM`.
- Second, reading two bytes to check formatted chars is `42` and the format will be the big or little endian format.

### CODE REVIEW

**Comment by odan** [comment]
TIFF is already supported :-)

**Comment by peter279k** [comment]
I know that and I enhance original approach.

**Comment by odan** [comment]
Before we add more complexity we should ask what kind of problem does it solve? 
Do you think the current solution does't detects the TIFF correctly? Is there a bug? 
Does it really matter for the image detection weather its has little endian or not? I think not.

**Comment by peter279k** [comment]
@odan, ok. That's right.

Reading the next 2 bytes seems that detecting the `TIFF` image in advanced, and it's optional work.

**Pull request closed without merging**
